spring:
  datasource:
    url: jdbc:mysql://localhost:3306/footfusionDB
    username: [username]
    password: [password]

  jpa:
    hibernate.ddl-auto: update

    database: mysql

logging:
  level:
    org.springframework.security: DEBUG