spring:
  datasource:
    url: jdbc:mysql://localhost:3306/footfusionDB
    username: root
    password: Aayushi@2022

  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect
    hibernate.ddl-auto: update

    database: mysql