spring:
  datasource:
    url: jdbc:mysql://localhost:3306/footfusionDB
    username: [username]
    password: [password]

  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    database: mysql

logging:
  level:
    org.springframework.security: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
